import "./globals.css";
// import PostJsonData from "./[locale]/postJsonData";
import { WrapperQueryClientProvider } from "@/tanstack-provider/queryProvider";
import { geistSans, geistMono } from "@/fonts-google/fonts";
import type { Metadata } from "next";
import { UrqlProvider } from "@/ui/components/providers/urqlProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`
      ${geistSans.variable} 
      ${geistMono.variable}
    `}>
      <body>
        {/* <PostJsonData url={"/api/freelancer/invoices"} /> */}
        <WrapperQueryClientProvider>
          <UrqlProvider>
            {children}
          </UrqlProvider>
        </WrapperQueryClientProvider>
      </body>
    </html>
  );
}
