import "./globals.css";
import { WrapperQueryClientProvider } from "@/tanstack-provider/queryProvider";
import { geistSans, geistMono } from "@/fonts-google/fonts";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`
      ${geistSans.variable} 
      ${geistMono.variable}
    `}>
      <body>
        <WrapperQueryClientProvider>
          {children}
        </WrapperQueryClientProvider>
      </body>
    </html>
  );
}
